[package]
name = "ibapi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A Rust port of the Interactive Brokers TWS API."
repository = "https://github.com/wvietor/ibkr-tws-api"
keywords = ["trading", "interactive_brokers", "IBKR"]
categories = ["finance"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibapi_derive = { version="0.1.0", path="src/ibkr_tws_api_derive" }
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["full"] }
toml = "0.7.4"
serde = { version = "1.0.163", features = ["derive"] }
chrono = "0.4.26"
crossbeam = "0.8.2"
bytes = "1.4.0"
anyhow = "1.0.71"
tracing = "0.1.37"
