[package]
name = "ibapi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A Rust port of the Interactive Brokers TWS API."
repository = "https://github.com/wvietor/ibkr-tws-api"
keywords = ["trading", "interactive_brokers", "IBKR"]
categories = ["finance"]


[dependencies]
ibapi_macros = { version="0.1.0", path= "../ibkr_rust_macros" }
tokio = { version = "1.35.1", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
toml = "0.8.8"
serde = { version = "1.0.195", features = ["derive"] }
chrono = "0.4.31"
crossbeam = "0.8.4"
bytes = "1.5.0"
anyhow = "1.0.79"
itoa = "1.0.10"
ryu = "1.0.16"
trait-variant = "0.1.1"
